apt install texlive-latex-base
apt install texlive-fonts-recommended
apt install texlive-fonts-extra
apt install texlive-latex-extra
apt install texlive-lang-portuguese
pip install requests
pip install pyyaml
pip install slackclient
pip install gitpython
