apt install texlive-latex-base
apt install texlive-fonts-recommended
apt install texlive-fonts-extra
apt install texlive-latex-extra
apt install texlive-lang-portuguese
apt install gnuplot5-x11
apt install xclip
pip install requests
pip install pyyaml
pip install slackclient
pip install gitpython
